volumes:
  mysql_data: {}

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: techchallenge
      MYSQL_USER: techchallenge
      MYSQL_PASSWORD: techchallenge
      MYSQL_ROOT_PASSWORD: techchallenge
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-ptechchallenge" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tech_challenge:
    build:
      context: .
      dockerfile: Dockerfile
    image: gastro_sys:1
    container_name: tech_challenge
    restart: always
    environment:
      - SPRING_DATASOURCE_USERNAME=techchallenge
      - SPRING_DATASOURCE_PASSWORD=techchallenge
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/techchallenge
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy